{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloud.game",
    "module": "gamepadlib",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gamepadlib-1.3.5.aar",
          "url": "gamepadlib-1.3.5.aar",
          "size": 175372,
          "sha512": "0489cebfefbaa4b4a0942381a67b6cdbf4544115d9680d36e3dd7b8d1fbd32af2618952735a95a9a40cf87f56b89b813d9dd3b728d32b463a12813412b99f184",
          "sha256": "f8f42d927beed5a0497fe7758f298cfaf8d2c32ad9e4c61b86f6f764c289ee09",
          "sha1": "2184fa53f19683281a5b0a4525b97a75efc10638",
          "md5": "9ced07cc905678b65429ef8a88d5f5b1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gamepadlib-1.3.5.aar",
          "url": "gamepadlib-1.3.5.aar",
          "size": 175372,
          "sha512": "0489cebfefbaa4b4a0942381a67b6cdbf4544115d9680d36e3dd7b8d1fbd32af2618952735a95a9a40cf87f56b89b813d9dd3b728d32b463a12813412b99f184",
          "sha256": "f8f42d927beed5a0497fe7758f298cfaf8d2c32ad9e4c61b86f6f764c289ee09",
          "sha1": "2184fa53f19683281a5b0a4525b97a75efc10638",
          "md5": "9ced07cc905678b65429ef8a88d5f5b1"
        }
      ]
    }
  ]
}
