{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloud.game",
    "module": "gamelib",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gamelib-1.3.5.aar",
          "url": "gamelib-1.3.5.aar",
          "size": 6884672,
          "sha512": "c373da8c49d8e3361864a5b0852ee2b1bdc9caa472abfb8b6f4a3da2f25681f751b817b7e483120db46b9f3dc7f0b1db85da2a19b987ea4c156cf019ebfea9e1",
          "sha256": "3bb73c3107e2620ea91e1b896a29b706ae4dcd6e707384b570fb9677a5a197f1",
          "sha1": "f900d0a8c51054197dd38533ec8c516f038248e1",
          "md5": "70afafa96c3552a923e142a9b8700fcf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.tcr",
          "module": "tcrsdk-full",
          "version": {
            "requires": "3.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "gamelib-1.3.5.aar",
          "url": "gamelib-1.3.5.aar",
          "size": 6884672,
          "sha512": "c373da8c49d8e3361864a5b0852ee2b1bdc9caa472abfb8b6f4a3da2f25681f751b817b7e483120db46b9f3dc7f0b1db85da2a19b987ea4c156cf019ebfea9e1",
          "sha256": "3bb73c3107e2620ea91e1b896a29b706ae4dcd6e707384b570fb9677a5a197f1",
          "sha1": "f900d0a8c51054197dd38533ec8c516f038248e1",
          "md5": "70afafa96c3552a923e142a9b8700fcf"
        }
      ]
    }
  ]
}
